#!/usr/bin/env python3
"""Read slicer settings out of a .3mf project file.

A .3mf is a zip. Alongside the geometry, slicers store the settings the project
was sliced with, which means a project file downloaded from Printables or
MakerWorld already carries its author's profile. That is usually easier for
someone to produce than an exported config bundle: everybody has .3mf files,
far fewer people know where the config export lives in the menus.

The two slicers write different files in different formats:

    PrusaSlicer   Metadata/Slic3r_PE.config        "; key = value" lines
    OrcaSlicer    Metadata/project_settings.config JSON object

BambuStudio uses the OrcaSlicer layout; OrcaSlicer is a fork of it.
"""

import json
import zipfile
from pathlib import Path

PRUSA_CONFIG = "Metadata/Slic3r_PE.config"
ORCA_CONFIG = "Metadata/project_settings.config"

PRUSASLICER = "prusaslicer"
ORCASLICER = "orcaslicer"


class NotAProject(Exception):
    """The file is a .3mf but carries no slicer settings.

    Exporters that only write geometry produce these - a mesh, no profile.
    There is nothing to convert, and saying so is more useful than returning an
    empty profile.
    """


def detect_flavour(path):
    """Return which slicer wrote this .3mf, or None if it carries no settings."""
    with zipfile.ZipFile(path) as archive:
        names = set(archive.namelist())
    if ORCA_CONFIG in names:
        return ORCASLICER
    if PRUSA_CONFIG in names:
        return PRUSASLICER
    return None


def parse_prusa_config(raw):
    """Parse PrusaSlicer's embedded config.

    Every line is a G-code comment, "; key = value", and there are no section
    headers: a project has exactly one resolved profile rather than the named
    print/filament/printer sections a config bundle carries.
    """
    settings = {}
    for line in raw.splitlines():
        line = line.lstrip(";").strip()
        if not line or "=" not in line or line.startswith("generated by"):
            continue
        key, _, value = line.partition("=")
        settings[key.strip()] = value.strip()
    return settings


def read_settings(path):
    """Return (flavour, settings) for a .3mf project file.

    Values are returned as the file stores them, including OrcaSlicer's
    single-element lists for per-extruder settings, so callers can tell a list
    from a scalar.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Fichier introuvable : {path}")
    if not zipfile.is_zipfile(path):
        raise NotAProject(f"{path.name} n'est pas une archive .3mf valide")

    flavour = detect_flavour(path)
    if flavour is None:
        raise NotAProject(
            f"{path.name} ne contient aucun réglage de slicer. "
            "C'est probablement un export de géométrie seule."
        )

    with zipfile.ZipFile(path) as archive:
        if flavour == ORCASLICER:
            raw = archive.read(ORCA_CONFIG).decode("utf-8", "replace")
            return flavour, json.loads(raw)
        raw = archive.read(PRUSA_CONFIG).decode("utf-8", "replace")
        return flavour, parse_prusa_config(raw)


def project_name(path):
    """A usable profile name for a project that carries none of its own."""
    return Path(path).stem
