"""Tests for 3MF reading and the OrcaSlicer -> PrusaSlicer direction.

The round-trip test is the important one. Converting a profile to OrcaSlicer
and back should land on the settings it started from, and anything that does
not is either a mapping bug or a genuine loss that the conversion report has to
declare. Measuring it here means a change to convert.py that quietly breaks the
reverse direction fails the build instead of reaching users.
"""

import json
import tempfile
import unittest
import zipfile
from pathlib import Path

import threemf
import to_prusa
from convert import (ConversionLog, convert_filament_profile,
                     convert_print_profile, convert_printer_profile)

FIXTURE = Path(__file__).parent / "fixtures" / "sample_safe.ini"

PRUSA_CONFIG_SAMPLE = """; generated by PrusaSlicer 2.9.4 on 2026-03-26 at 21:10:08 UTC

; layer_height = 0.2
; perimeters = 3
; fill_density = 15%
; fill_pattern = gyroid
; temperature = 215
; bed_temperature = 60
; filament_type = PLA
; nozzle_diameter = 0.4
; bed_shape = 0x0,250x0,250x210,0x210
"""

ORCA_CONFIG_SAMPLE = {
    "layer_height": "0.2",
    "wall_loops": "3",
    "sparse_infill_density": "15%",
    "sparse_infill_pattern": "gyroid",
    "nozzle_temperature": ["215"],
    "hot_plate_temp": ["60"],
    "filament_type": ["PLA"],
    "nozzle_diameter": ["0.4"],
    "printable_area": ["0x0", "250x0", "250x210", "0x210"],
}


def _make_3mf(path, extra_files):
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("[Content_Types].xml", "<Types/>")
        archive.writestr("3D/3dmodel.model", "<model/>")
        for name, content in extra_files.items():
            archive.writestr(name, content)


class ThreeMfTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.dir = Path(self.tmp.name)

    def test_reads_a_prusaslicer_project(self):
        path = self.dir / "prusa.3mf"
        _make_3mf(path, {threemf.PRUSA_CONFIG: PRUSA_CONFIG_SAMPLE})

        flavour, settings = threemf.read_settings(path)

        self.assertEqual(flavour, threemf.PRUSASLICER)
        self.assertEqual(settings["layer_height"], "0.2")
        self.assertEqual(settings["fill_pattern"], "gyroid")
        self.assertEqual(settings["bed_shape"], "0x0,250x0,250x210,0x210")
        # The "generated by" banner is a comment, not a setting.
        self.assertNotIn("generated by PrusaSlicer 2.9.4 on 2026-03-26 at", settings)

    def test_reads_an_orcaslicer_project(self):
        path = self.dir / "orca.3mf"
        _make_3mf(path, {threemf.ORCA_CONFIG: json.dumps(ORCA_CONFIG_SAMPLE)})

        flavour, settings = threemf.read_settings(path)

        self.assertEqual(flavour, threemf.ORCASLICER)
        # Per-extruder settings stay lists so callers can tell them apart.
        self.assertEqual(settings["nozzle_temperature"], ["215"])

    def test_geometry_only_project_is_rejected(self):
        path = self.dir / "mesh.3mf"
        _make_3mf(path, {})
        with self.assertRaises(threemf.NotAProject):
            threemf.read_settings(path)

    def test_non_archive_is_rejected(self):
        path = self.dir / "broken.3mf"
        path.write_text("pas une archive", encoding="utf-8")
        with self.assertRaises(threemf.NotAProject):
            threemf.read_settings(path)


class KeyMapTests(unittest.TestCase):
    def test_map_is_discovered_from_the_forward_converters(self):
        key_map = to_prusa.build_key_map()
        # A refactor of convert.py that broke discovery would empty this.
        self.assertGreater(len(key_map), 200)
        self.assertEqual(key_map["layer_height"], ("layer_height", "process"))
        self.assertEqual(key_map["wall_loops"], ("perimeters", "process"))
        self.assertEqual(key_map["nozzle_diameter"][1], "printer")

    def test_ambiguous_keys_are_identified(self):
        ambiguous = to_prusa.build_ambiguous_keys()
        # Several PrusaSlicer fan settings collapse onto one Orca setting; the
        # reverse cannot tell them apart and has to say so.
        self.assertIn("overhang_fan_speed", ambiguous)
        self.assertGreater(len(ambiguous["overhang_fan_speed"]), 1)


class ReverseConversionTests(unittest.TestCase):
    def test_values_survive_the_reverse(self):
        sections, unknown = to_prusa.orca_to_prusa(ORCA_CONFIG_SAMPLE)
        self.assertEqual(sections["process"]["layer_height"], "0.2")
        self.assertEqual(sections["process"]["perimeters"], "3")
        self.assertEqual(sections["process"]["fill_pattern"], "gyroid")
        self.assertEqual(sections["filament"]["temperature"], "215")
        self.assertEqual(sections["filament"]["filament_type"], "PLA")
        self.assertEqual(unknown, [])

    def test_comma_separated_lists_are_rejoined(self):
        # printable_area is a split list on the Orca side, one string on the
        # PrusaSlicer side. Taking only the first entry would silently shrink
        # the bed to a point.
        sections, _ = to_prusa.orca_to_prusa(ORCA_CONFIG_SAMPLE)
        self.assertEqual(sections["printer"]["bed_shape"],
                         "0x0,250x0,250x210,0x210")

    def test_enum_transforms_are_inverted(self):
        cases = [
            ({"enable_arc_fitting": "1"}, "process", "arc_fitting", "enabled"),
            ({"enable_arc_fitting": "0"}, "process", "arc_fitting", "disabled"),
            ({"label_objects": "0"}, "process", "gcode_label_objects", "disabled"),
            ({"print_sequence": "by object"}, "process", "complete_objects", "1"),
            ({"ensure_vertical_shell_thickness": "none"}, "process",
             "ensure_vertical_shell_thickness", "disabled"),
            ({"support_interface_loop_pattern": "default"}, "process",
             "support_material_interface_contact_loops", "0"),
        ]
        for settings, section, key, expected in cases:
            with self.subTest(settings=settings):
                sections, _ = to_prusa.orca_to_prusa(settings)
                self.assertEqual(sections[section][key], expected)

    def test_ironing_restores_both_source_settings(self):
        # convert.py folds 'ironing' and 'ironing_type' into one Orca setting.
        off, _ = to_prusa.orca_to_prusa({"ironing_type": "no ironing"})
        self.assertEqual(off["process"]["ironing"], "0")

        on, _ = to_prusa.orca_to_prusa({"ironing_type": "top"})
        self.assertEqual(on["process"]["ironing"], "1")
        self.assertEqual(on["process"]["ironing_type"], "top")

    def test_unknown_keys_are_reported_not_dropped_silently(self):
        log = ConversionLog()
        _, unknown = to_prusa.orca_to_prusa(
            {"layer_height": "0.2", "some_bambu_only_setting": "1"}, log=log)
        self.assertEqual(unknown, ["some_bambu_only_setting"])
        self.assertTrue(any("sans équivalent" in w for w in log.warnings))


class RoundTripTests(unittest.TestCase):
    """Prusa -> Orca -> Prusa must land where it started."""

    def _forward(self, prusa_settings):
        log = ConversionLog()
        orca = {}
        orca.update(convert_print_profile(
            "x", prusa_settings, log.new_section("p", "process")))
        orca.update(convert_filament_profile(
            "x", prusa_settings, log.new_section("f", "filament")))
        orca.update(convert_printer_profile(
            "x", prusa_settings, log.new_section("pr", "printer")))
        return orca

    def test_settings_survive_a_round_trip(self):
        source = threemf.parse_prusa_config(PRUSA_CONFIG_SAMPLE)
        orca = self._forward(source)
        sections, _ = to_prusa.orca_to_prusa(orca)

        restored = {}
        for section in sections.values():
            restored.update(section)

        compared = set(restored) & set(source)
        self.assertTrue(compared, "the round trip restored nothing at all")
        differing = {k: (source[k], restored[k])
                     for k in compared if source[k] != restored[k]}
        self.assertEqual(differing, {}, f"round trip changed values: {differing}")

    def test_round_trip_over_the_shared_fixture(self):
        from convert import parse_ini

        sections = parse_ini(FIXTURE)
        printer = next(v for k, v in sections.items() if k.startswith("printer:"))
        orca = self._forward(printer)
        restored, _ = to_prusa.orca_to_prusa(orca)

        flat = {}
        for section in restored.values():
            flat.update(section)
        self.assertEqual(flat["nozzle_diameter"], "0.4")
        self.assertEqual(flat["gcode_flavor"], "marlin2")
        self.assertEqual(flat["bed_shape"], "0x0,250x0,250x210,0x210")


class BundleWritingTests(unittest.TestCase):
    def test_written_bundle_is_a_valid_ini(self):
        import configparser

        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        out = Path(tmp.name) / "bundle.ini"

        sections, _ = to_prusa.orca_to_prusa(ORCA_CONFIG_SAMPLE)
        to_prusa.write_ini_bundle(sections, "Test", out)

        # RawConfigParser: PrusaSlicer values contain % signs, which the
        # interpolating parser would try to expand.
        parser = configparser.RawConfigParser()
        parser.read(out, encoding="utf-8")
        self.assertEqual(
            sorted(parser.sections()),
            ["filament:Test", "presets", "print:Test", "printer:Test"])
        self.assertEqual(parser["print:Test"]["layer_height"], "0.2")
        self.assertEqual(parser["presets"]["print"], "Test")


if __name__ == "__main__":
    unittest.main()
